# Generated by Django 6.0.3 on 2026-03-30 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelescopeMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'telescope_monitoring',
            },
        ),
        migrations.CreateModel(
            name='TelescopeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('family_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Request'), (2, 'Query'), (3, 'Exception'), (4, 'Model'), (5, 'Log'), (6, 'Cache'), (7, 'Redis'), (8, 'Mail'), (9, 'View'), (10, 'Event'), (11, 'Command'), (12, 'Dump'), (13, 'Client Request'), (14, 'Gate'), (15, 'Notification'), (16, 'Schedule'), (17, 'Batch')], db_index=True)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'telescope_entries',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-created_at', 'type'], name='telescope_e_created_a92ce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelescopeEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='telescope.telescopeentry')),
            ],
            options={
                'db_table': 'telescope_entries_tags',
            },
        ),
    ]
